# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-21 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210221_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.FloatField(max_length=200),
        ),
    ]
