# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-21 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210221_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='lati',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longi',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
