# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-21 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210221_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('em_num', models.CharField(max_length=200)),
                ('reg', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('longi', models.FloatField(max_length=200)),
                ('lati', models.FloatField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Accident',
        ),
    ]
