# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-05 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210221_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidents',
            name='link',
            field=models.CharField(default='http://192.168.43.162:8081/', max_length=200),
        ),
    ]
