# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-15 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_accidents_status1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidents',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
