# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-10 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20220310_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
