# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-11 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20220310_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('hash1', models.CharField(max_length=200)),
                ('hash2', models.CharField(max_length=200)),
                ('distance', models.CharField(max_length=200)),
            ],
        ),
    ]
